/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XvancoaAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface XvancoaAmbulanceWlEditor {
        "entryId": string;
    }
    interface XvancoaAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface XvancoaAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXvancoaAmbulanceWlEditorElement;
}
export interface XvancoaAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXvancoaAmbulanceWlListElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXvancoaAmbulanceWlAppElement extends Components.XvancoaAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLXvancoaAmbulanceWlAppElement: {
        prototype: HTMLXvancoaAmbulanceWlAppElement;
        new (): HTMLXvancoaAmbulanceWlAppElement;
    };
    interface HTMLXvancoaAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXvancoaAmbulanceWlEditorElement extends Components.XvancoaAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXvancoaAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXvancoaAmbulanceWlEditorElement, ev: XvancoaAmbulanceWlEditorCustomEvent<HTMLXvancoaAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXvancoaAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXvancoaAmbulanceWlEditorElement, ev: XvancoaAmbulanceWlEditorCustomEvent<HTMLXvancoaAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXvancoaAmbulanceWlEditorElement: {
        prototype: HTMLXvancoaAmbulanceWlEditorElement;
        new (): HTMLXvancoaAmbulanceWlEditorElement;
    };
    interface HTMLXvancoaAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXvancoaAmbulanceWlListElement extends Components.XvancoaAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXvancoaAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXvancoaAmbulanceWlListElement, ev: XvancoaAmbulanceWlListCustomEvent<HTMLXvancoaAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXvancoaAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXvancoaAmbulanceWlListElement, ev: XvancoaAmbulanceWlListCustomEvent<HTMLXvancoaAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXvancoaAmbulanceWlListElement: {
        prototype: HTMLXvancoaAmbulanceWlListElement;
        new (): HTMLXvancoaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xvancoa-ambulance-wl-app": HTMLXvancoaAmbulanceWlAppElement;
        "xvancoa-ambulance-wl-editor": HTMLXvancoaAmbulanceWlEditorElement;
        "xvancoa-ambulance-wl-list": HTMLXvancoaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XvancoaAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface XvancoaAmbulanceWlEditor {
        "entryId"?: string;
        "onEditor-closed"?: (event: XvancoaAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface XvancoaAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: XvancoaAmbulanceWlListCustomEvent<string>) => void;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface XvancoaAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface XvancoaAmbulanceWlEditorAttributes {
        "entryId": string;
    }
    interface XvancoaAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "xvancoa-ambulance-wl-app": Omit<XvancoaAmbulanceWlApp, keyof XvancoaAmbulanceWlAppAttributes> & { [K in keyof XvancoaAmbulanceWlApp & keyof XvancoaAmbulanceWlAppAttributes]?: XvancoaAmbulanceWlApp[K] } & { [K in keyof XvancoaAmbulanceWlApp & keyof XvancoaAmbulanceWlAppAttributes as `attr:${K}`]?: XvancoaAmbulanceWlAppAttributes[K] } & { [K in keyof XvancoaAmbulanceWlApp & keyof XvancoaAmbulanceWlAppAttributes as `prop:${K}`]?: XvancoaAmbulanceWlApp[K] };
        "xvancoa-ambulance-wl-editor": Omit<XvancoaAmbulanceWlEditor, keyof XvancoaAmbulanceWlEditorAttributes> & { [K in keyof XvancoaAmbulanceWlEditor & keyof XvancoaAmbulanceWlEditorAttributes]?: XvancoaAmbulanceWlEditor[K] } & { [K in keyof XvancoaAmbulanceWlEditor & keyof XvancoaAmbulanceWlEditorAttributes as `attr:${K}`]?: XvancoaAmbulanceWlEditorAttributes[K] } & { [K in keyof XvancoaAmbulanceWlEditor & keyof XvancoaAmbulanceWlEditorAttributes as `prop:${K}`]?: XvancoaAmbulanceWlEditor[K] };
        "xvancoa-ambulance-wl-list": Omit<XvancoaAmbulanceWlList, keyof XvancoaAmbulanceWlListAttributes> & { [K in keyof XvancoaAmbulanceWlList & keyof XvancoaAmbulanceWlListAttributes]?: XvancoaAmbulanceWlList[K] } & { [K in keyof XvancoaAmbulanceWlList & keyof XvancoaAmbulanceWlListAttributes as `attr:${K}`]?: XvancoaAmbulanceWlListAttributes[K] } & { [K in keyof XvancoaAmbulanceWlList & keyof XvancoaAmbulanceWlListAttributes as `prop:${K}`]?: XvancoaAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xvancoa-ambulance-wl-app": LocalJSX.IntrinsicElements["xvancoa-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLXvancoaAmbulanceWlAppElement>;
            "xvancoa-ambulance-wl-editor": LocalJSX.IntrinsicElements["xvancoa-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLXvancoaAmbulanceWlEditorElement>;
            "xvancoa-ambulance-wl-list": LocalJSX.IntrinsicElements["xvancoa-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXvancoaAmbulanceWlListElement>;
        }
    }
}
